name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate snake game from GitHub contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: DuvinduDinethminDevendra
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#7ac143&color_dots=#151515,#1b1f23,#0e4429,#006d32,#26a641
            dist/github-contribution-grid-snake-dark.svg?color_snake=#7ac143&color_dots=#000000,#0a0a0a,#004d00,#008000,#00ff00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push snake to GitHub Pages
        uses: Platane/snk/svg-only@v2.3.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

this is white make it dark
