name: Generate Snake Animation
on:
  # Run this action on a schedule (once every 6 hours)
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow running this action manually from the Actions tab
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    
    # This gives the action permission to write to the repo
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DuvinduDinethminDevendra
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Dark theme with custom colors
          # Using a very dark background with bright green snake
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00ff41&color_dots=#0d1117,#161b22,#1f6feb,#39d353,#39d353
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#00ff41&color_dots=#0d1117,#161b22,#1f6feb,#39d353,#39d353
      
      - name: Deploy snake file to 'output' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: dist
