name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DuvinduDinethminDevendra
          # Use gif_out_path for animated GIF
          gif_out_path: dist/github-contribution-grid-snake.gif
          
          # Custom background and dots using SVG parameters
          outputs: |
            dist/github-contribution-grid-snake.svg?
            palette=github-dark&
            background=00000000& # Transparent background (will blend with GitHub's dark mode)
            color_snake=green& # Green snake
            color_dots=#00FF00 # Bright green dots
